<?php
/**
 * OmniXEP Internationalization (i18n) System
 * Supports 15 languages with English as default
 */
defined('ABSPATH') || exit;

function omnixep_get_current_lang() {
    return get_option('omnixep_admin_language', 'en');
}

function omnixep_get_languages() {
    return array(
        'en' => array('name' => 'English',    'flag' => '🇬🇧'),
        'tr' => array('name' => 'Türkçe',     'flag' => '🇹🇷'),
        'de' => array('name' => 'Deutsch',     'flag' => '🇩🇪'),
        'fr' => array('name' => 'Français',    'flag' => '🇫🇷'),
        'es' => array('name' => 'Español',     'flag' => '🇪🇸'),
        'pt' => array('name' => 'Português',   'flag' => '🇵🇹'),
        'it' => array('name' => 'Italiano',    'flag' => '🇮🇹'),
        'nl' => array('name' => 'Nederlands',  'flag' => '🇳🇱'),
        'ru' => array('name' => 'Русский',     'flag' => '🇷🇺'),
        'zh' => array('name' => '中文',         'flag' => '🇨🇳'),
        'ja' => array('name' => '日本語',       'flag' => '🇯🇵'),
        'ko' => array('name' => '한국어',       'flag' => '🇰🇷'),
        'ar' => array('name' => 'العربية',     'flag' => '🇸🇦'),
        'hi' => array('name' => 'हिन्दी',       'flag' => '🇮🇳'),
        'pl' => array('name' => 'Polski',      'flag' => '🇵🇱'),
    );
}

function omnixep_get_translations() {
    return array(
        // Admin Settings - Form Fields
        'Enable/Disable' => array('tr'=>'Etkinleştir/Devre Dışı','de'=>'Aktivieren/Deaktivieren','fr'=>'Activer/Désactiver','es'=>'Activar/Desactivar','pt'=>'Ativar/Desativar','it'=>'Abilita/Disabilita','nl'=>'Inschakelen/Uitschakelen','ru'=>'Включить/Отключить','zh'=>'启用/禁用','ja'=>'有効/無効','ko'=>'활성화/비활성화','ar'=>'تفعيل/تعطيل','hi'=>'सक्षम/अक्षम','pl'=>'Włącz/Wyłącz'),
        'Enable OmniXEP Payment' => array('tr'=>'OmniXEP Ödemeyi Etkinleştir','de'=>'OmniXEP-Zahlung aktivieren','fr'=>'Activer le paiement OmniXEP','es'=>'Activar pago OmniXEP','pt'=>'Ativar pagamento OmniXEP','it'=>'Abilita pagamento OmniXEP','nl'=>'OmniXEP-betaling inschakelen','ru'=>'Включить оплату OmniXEP','zh'=>'启用OmniXEP支付','ja'=>'OmniXEP決済を有効にする','ko'=>'OmniXEP 결제 활성화','ar'=>'تفعيل دفع OmniXEP','hi'=>'OmniXEP भुगतान सक्षम करें','pl'=>'Włącz płatność OmniXEP'),
        'Title' => array('tr'=>'Başlık','de'=>'Titel','fr'=>'Titre','es'=>'Título','pt'=>'Título','it'=>'Titolo','nl'=>'Titel','ru'=>'Заголовок','zh'=>'标题','ja'=>'タイトル','ko'=>'제목','ar'=>'العنوان','hi'=>'शीर्षक','pl'=>'Tytuł'),
        'Description' => array('tr'=>'Açıklama','de'=>'Beschreibung','fr'=>'Description','es'=>'Descripción','pt'=>'Descrição','it'=>'Descrizione','nl'=>'Beschrijving','ru'=>'Описание','zh'=>'描述','ja'=>'説明','ko'=>'설명','ar'=>'الوصف','hi'=>'विवरण','pl'=>'Opis'),
        'Merchant Wallet Address' => array('tr'=>'Satıcı Cüzdan Adresi','de'=>'Händler-Wallet-Adresse','fr'=>'Adresse du portefeuille marchand','es'=>'Dirección de billetera del comerciante','pt'=>'Endereço da carteira do comerciante','it'=>'Indirizzo portafoglio commerciante','nl'=>'Handelaar portemonnee-adres','ru'=>'Адрес кошелька продавца','zh'=>'商户钱包地址','ja'=>'販売者ウォレットアドレス','ko'=>'판매자 지갑 주소','ar'=>'عنوان محفظة التاجر','hi'=>'व्यापारी वॉलेट पता','pl'=>'Adres portfela sprzedawcy'),
        'Fee Wallet Address' => array('tr'=>'Ücret Cüzdan Adresi','de'=>'Gebühren-Wallet-Adresse','fr'=>'Adresse du portefeuille de frais','es'=>'Dirección de billetera de comisiones','pt'=>'Endereço da carteira de taxas','it'=>'Indirizzo portafoglio commissioni','nl'=>'Kosten portemonnee-adres','ru'=>'Адрес кошелька комиссий','zh'=>'手续费钱包地址','ja'=>'手数料ウォレットアドレス','ko'=>'수수료 지갑 주소','ar'=>'عنوان محفظة الرسوم','hi'=>'शुल्क वॉलेट पता','pl'=>'Adres portfela opłat'),
        'Fee Wallet Generator' => array('tr'=>'Ücret Cüzdan Oluşturucu','de'=>'Gebühren-Wallet-Generator','fr'=>'Générateur de portefeuille de frais','es'=>'Generador de billetera de comisiones','pt'=>'Gerador de carteira de taxas','it'=>'Generatore portafoglio commissioni','nl'=>'Kosten portemonnee-generator','ru'=>'Генератор кошелька комиссий','zh'=>'手续费钱包生成器','ja'=>'手数料ウォレット生成','ko'=>'수수료 지갑 생성기','ar'=>'مولد محفظة الرسوم','hi'=>'शुल्क वॉलेट जनरेटर','pl'=>'Generator portfela opłat'),
        'Fee Wallet Daily Limit' => array('tr'=>'Ücret Cüzdan Günlük Limiti','de'=>'Tägliches Gebühren-Wallet-Limit','fr'=>'Limite quotidienne du portefeuille','es'=>'Límite diario de billetera','pt'=>'Limite diário da carteira','it'=>'Limite giornaliero portafoglio','nl'=>'Dagelijks portemonnee-limiet','ru'=>'Дневной лимит кошелька','zh'=>'手续费钱包每日限额','ja'=>'手数料ウォレット日次上限','ko'=>'수수료 지갑 일일 한도','ar'=>'الحد اليومي لمحفظة الرسوم','hi'=>'शुल्क वॉलेट दैनिक सीमा','pl'=>'Dzienny limit portfela opłat'),
        'Token Configuration' => array('tr'=>'Token Yapılandırması','de'=>'Token-Konfiguration','fr'=>'Configuration des jetons','es'=>'Configuración de tokens','pt'=>'Configuração de tokens','it'=>'Configurazione token','nl'=>'Token-configuratie','ru'=>'Настройка токенов','zh'=>'代币配置','ja'=>'トークン設定','ko'=>'토큰 구성','ar'=>'تكوين الرمز','hi'=>'टोकन कॉन्फ़िगरेशन','pl'=>'Konfiguracja tokenów'),
        'Order Status After Payment' => array('tr'=>'Ödeme Sonrası Sipariş Durumu','de'=>'Bestellstatus nach Zahlung','fr'=>'Statut après paiement','es'=>'Estado del pedido tras el pago','pt'=>'Status do pedido após pagamento','it'=>'Stato ordine dopo pagamento','nl'=>'Bestelstatus na betaling','ru'=>'Статус заказа после оплаты','zh'=>'付款后订单状态','ja'=>'支払い後の注文ステータス','ko'=>'결제 후 주문 상태','ar'=>'حالة الطلب بعد الدفع','hi'=>'भुगतान के बाद ऑर्डर स्थिति','pl'=>'Status zamówienia po płatności'),
        'Invoice Information (For Commission)' => array('tr'=>'Fatura Bilgileri (Komisyon İçin)','de'=>'Rechnungsinformationen (Für Provision)','fr'=>'Informations de facturation (Pour commission)','es'=>'Información de factura (Para comisión)','pt'=>'Informações da fatura (Para comissão)','it'=>'Informazioni fattura (Per commissione)','nl'=>'Factuurinformatie (Voor commissie)','ru'=>'Информация о счёте (Для комиссии)','zh'=>'发票信息（佣金用）','ja'=>'請求書情報（手数料用）','ko'=>'청구서 정보 (수수료용)','ar'=>'معلومات الفاتورة (للعمولة)','hi'=>'चालान जानकारी (कमीशन के लिए)','pl'=>'Informacje o fakturze (Dla prowizji)'),
        'Full Name / Company Name' => array('tr'=>'Ad Soyad / Şirket Adı','de'=>'Vollständiger Name / Firmenname','fr'=>'Nom complet / Raison sociale','es'=>'Nombre completo / Razón social','pt'=>'Nome completo / Razão social','it'=>'Nome completo / Ragione sociale','nl'=>'Volledige naam / Bedrijfsnaam','ru'=>'Полное имя / Название компании','zh'=>'全名/公司名称','ja'=>'氏名/会社名','ko'=>'성명/회사명','ar'=>'الاسم الكامل / اسم الشركة','hi'=>'पूरा नाम / कंपनी का नाम','pl'=>'Imię i nazwisko / Nazwa firmy'),
        'Site Address' => array('tr'=>'Site Adresi','de'=>'Siteadresse','fr'=>'Adresse du site','es'=>'Dirección del sitio','pt'=>'Endereço do site','it'=>'Indirizzo del sito','nl'=>'Siteadres','ru'=>'Адрес сайта','zh'=>'网站地址','ja'=>'サイトアドレス','ko'=>'사이트 주소','ar'=>'عنوان الموقع','hi'=>'साइट पता','pl'=>'Adres strony'),
        'Email Address' => array('tr'=>'E-posta Adresi','de'=>'E-Mail-Adresse','fr'=>'Adresse e-mail','es'=>'Correo electrónico','pt'=>'Endereço de e-mail','it'=>'Indirizzo e-mail','nl'=>'E-mailadres','ru'=>'Адрес электронной почты','zh'=>'电子邮件地址','ja'=>'メールアドレス','ko'=>'이메일 주소','ar'=>'عنوان البريد الإلكتروني','hi'=>'ईमेल पता','pl'=>'Adres e-mail'),
        'Tax ID / VAT Number' => array('tr'=>'Vergi No / KDV Numarası','de'=>'Steuer-ID / USt-IdNr.','fr'=>'Numéro fiscal / TVA','es'=>'NIF / Número de IVA','pt'=>'NIF / Número de IVA','it'=>'Codice fiscale / Partita IVA','nl'=>'BTW-nummer','ru'=>'ИНН / НДС номер','zh'=>'税号/增值税号','ja'=>'納税者番号/VAT番号','ko'=>'세금 ID / VAT 번호','ar'=>'الرقم الضريبي / رقم ضريبة القيمة المضافة','hi'=>'कर आईडी / वैट नंबर','pl'=>'NIP / Numer VAT'),
        'Entity Type' => array('tr'=>'Kurum Türü','de'=>'Unternehmensart','fr'=>'Type d\'entité','es'=>'Tipo de entidad','pt'=>'Tipo de entidade','it'=>'Tipo di ente','nl'=>'Entiteitstype','ru'=>'Тип организации','zh'=>'实体类型','ja'=>'法人形態','ko'=>'법인 유형','ar'=>'نوع الكيان','hi'=>'इकाई प्रकार','pl'=>'Typ podmiotu'),
        'Individual' => array('tr'=>'Bireysel','de'=>'Einzelperson','fr'=>'Individuel','es'=>'Individual','pt'=>'Individual','it'=>'Individuale','nl'=>'Individueel','ru'=>'Физическое лицо','zh'=>'个人','ja'=>'個人','ko'=>'개인','ar'=>'فرد','hi'=>'व्यक्तिगत','pl'=>'Indywidualny'),
        'Company / Corporate' => array('tr'=>'Şirket / Kurumsal','de'=>'Unternehmen','fr'=>'Entreprise','es'=>'Empresa / Corporativo','pt'=>'Empresa / Corporativo','it'=>'Azienda / Societario','nl'=>'Bedrijf','ru'=>'Компания','zh'=>'公司/企业','ja'=>'法人/企業','ko'=>'회사/기업','ar'=>'شركة / مؤسسة','hi'=>'कंपनी / कॉर्पोरेट','pl'=>'Firma / Korporacja'),
        'Country' => array('tr'=>'Ülke','de'=>'Land','fr'=>'Pays','es'=>'País','pt'=>'País','it'=>'Paese','nl'=>'Land','ru'=>'Страна','zh'=>'国家','ja'=>'国','ko'=>'국가','ar'=>'البلد','hi'=>'देश','pl'=>'Kraj'),
        'Billing Address' => array('tr'=>'Fatura Adresi','de'=>'Rechnungsadresse','fr'=>'Adresse de facturation','es'=>'Dirección de facturación','pt'=>'Endereço de faturação','it'=>'Indirizzo di fatturazione','nl'=>'Factuuradres','ru'=>'Платёжный адрес','zh'=>'账单地址','ja'=>'請求先住所','ko'=>'청구 주소','ar'=>'عنوان الفاتورة','hi'=>'बिलिंग पता','pl'=>'Adres rozliczeniowy'),
        'Terms Acceptance Status' => array('tr'=>'Şartlar Kabul Durumu','de'=>'Status der AGB-Akzeptanz','fr'=>'Statut d\'acceptation des conditions','es'=>'Estado de aceptación de términos','pt'=>'Estado de aceitação dos termos','it'=>'Stato accettazione termini','nl'=>'Status voorwaardenacceptatie','ru'=>'Статус принятия условий','zh'=>'条款接受状态','ja'=>'利用規約同意状況','ko'=>'약관 동의 상태','ar'=>'حالة قبول الشروط','hi'=>'शर्तों की स्वीकृति स्थिति','pl'=>'Status akceptacji regulaminu'),

        // Form field descriptions
        'Current terms of service acceptance information.' => array('tr'=>'Mevcut hizmet şartları kabul bilgileri.','de'=>'Aktuelle AGB-Akzeptanzinformationen.','fr'=>'Informations d\'acceptation des conditions de service.','es'=>'Información de aceptación de términos de servicio.','pt'=>'Informações de aceitação dos termos de serviço.','it'=>'Informazioni sull\'accettazione dei termini di servizio.','nl'=>'Huidige acceptatie-informatie van servicevoorwaarden.','ru'=>'Информация о принятии условий обслуживания.','zh'=>'当前服务条款接受信息。','ja'=>'現在の利用規約の承諾情報。','ko'=>'현재 서비스 약관 동의 정보.','ar'=>'معلومات قبول شروط الخدمة الحالية.','hi'=>'वर्तमान सेवा शर्तों की स्वीकृति जानकारी।','pl'=>'Aktualne informacje o akceptacji regulaminu.'),
        'This controls the title which the user sees during checkout.' => array('tr'=>'Bu, müşterinin ödeme sırasında gördüğü başlığı kontrol eder.','de'=>'Steuert den Titel, den der Benutzer beim Checkout sieht.','fr'=>'Contrôle le titre que l\'utilisateur voit lors du paiement.','es'=>'Controla el título que el usuario ve durante el pago.','pt'=>'Controla o título que o usuário vê no checkout.','it'=>'Controlla il titolo che l\'utente vede durante il checkout.','nl'=>'Bepaalt de titel die de gebruiker ziet bij het afrekenen.','ru'=>'Управляет заголовком, который видит пользователь при оплате.','zh'=>'控制用户结账时看到的标题。','ja'=>'チェックアウト時にユーザーに表示されるタイトルを制御します。','ko'=>'결제 시 사용자에게 표시되는 제목을 제어합니다.','ar'=>'يتحكم في العنوان الذي يراه المستخدم أثناء الدفع.','hi'=>'चेकआउट के दौरान उपयोगकर्ता को दिखाई देने वाले शीर्षक को नियंत्रित करता है।','pl'=>'Kontroluje tytuł widoczny dla użytkownika podczas płatności.'),
        'Payment method description that the customer will see on your checkout.' => array('tr'=>'Müşterinin ödeme sayfasında göreceği ödeme yöntemi açıklaması.','de'=>'Beschreibung der Zahlungsmethode, die der Kunde beim Checkout sieht.','fr'=>'Description du mode de paiement visible par le client.','es'=>'Descripción del método de pago que verá el cliente.','pt'=>'Descrição do método de pagamento que o cliente verá.','it'=>'Descrizione del metodo di pagamento visibile al cliente.','nl'=>'Beschrijving van de betaalmethode die de klant ziet.','ru'=>'Описание способа оплаты, которое увидит клиент.','zh'=>'客户在结账页面看到的支付方式说明。','ja'=>'チェックアウトで顧客に表示される支払い方法の説明。','ko'=>'결제 페이지에서 고객이 보게 될 결제 방법 설명.','ar'=>'وصف طريقة الدفع الذي سيراه العميل.','hi'=>'भुगतान विधि का विवरण जो ग्राहक चेकआउट पर देखेगा।','pl'=>'Opis metody płatności widoczny dla klienta.'),
        'Your main wallet address where customer payments will be sent. This can be a cold wallet - no mnemonic storage required.' => array('tr'=>'Müşteri ödemelerinin gönderileceği ana cüzdan adresiniz. Soğuk cüzdan olabilir - anımsatıcı sözcük gerekmez.','de'=>'Ihre Haupt-Wallet-Adresse für Kundenzahlungen. Kann eine Cold Wallet sein.','fr'=>'Adresse principale pour recevoir les paiements. Peut être un portefeuille froid.','es'=>'Dirección principal para recibir pagos. Puede ser una billetera fría.','pt'=>'Endereço principal para receber pagamentos. Pode ser uma carteira fria.','it'=>'Indirizzo principale per ricevere pagamenti. Può essere un cold wallet.','nl'=>'Uw hoofdadres voor klantbetalingen. Kan een cold wallet zijn.','ru'=>'Основной адрес кошелька для приёма платежей. Может быть холодным кошельком.','zh'=>'接收客户付款的主钱包地址，可以是冷钱包。','ja'=>'顧客からの支払いを受け取るメインウォレットアドレス。コールドウォレット可。','ko'=>'고객 결제를 수신할 메인 지갑 주소. 콜드 월렛 사용 가능.','ar'=>'عنوان المحفظة الرئيسي لاستقبال المدفوعات. يمكن أن تكون محفظة باردة.','hi'=>'ग्राहक भुगतान प्राप्त करने के लिए मुख्य वॉलेट पता। कोल्ड वॉलेट हो सकता है।','pl'=>'Główny adres portfela do odbioru płatności. Może być portfelem zimnym.'),
        'Separate wallet for paying 0.8% commission fees. This wallet\'s mnemonic is stored encrypted in browser.' => array('tr'=>'%0.8 komisyon ücreti ödemek için ayrı cüzdan. Bu cüzdanın anımsatıcı sözcükleri tarayıcıda şifreli olarak saklanır.','de'=>'Separates Wallet für 0,8% Provisionsgebühren. Die Mnemonik wird verschlüsselt im Browser gespeichert.','fr'=>'Portefeuille séparé pour les frais de commission de 0,8%. Le mnémonique est stocké chiffré dans le navigateur.','es'=>'Billetera separada para comisiones del 0,8%. El mnemónico se almacena cifrado en el navegador.','pt'=>'Carteira separada para taxas de comissão de 0,8%. O mnemônico é armazenado criptografado no navegador.','it'=>'Portafoglio separato per commissioni dello 0,8%. Il mnemonico è crittografato nel browser.','nl'=>'Apart portemonnee voor 0,8% commissiekosten. De mnemonische zin wordt versleuteld opgeslagen in de browser.','ru'=>'Отдельный кошелёк для уплаты комиссии 0,8%. Мнемоника хранится зашифрованной в браузере.','zh'=>'用于支付0.8%佣金的独立钱包。助记词加密存储在浏览器中。','ja'=>'手数料0.8%支払い用の別ウォレット。ニーモニックはブラウザに暗号化保存。','ko'=>'0.8% 수수료 결제용 별도 지갑. 니모닉은 브라우저에 암호화 저장됩니다.','ar'=>'محفظة منفصلة لدفع عمولة 0.8%. يتم تخزين الكلمات المفتاحية مشفرة في المتصفح.','hi'=>'0.8% कमीशन शुल्क के लिए अलग वॉलेट। स्मरणीय शब्द ब्राउज़र में एन्क्रिप्टेड संग्रहीत।','pl'=>'Oddzielny portfel na prowizję 0,8%. Mnemonik jest przechowywany zaszyfrowany w przeglądarce.'),
        'Maximum XEP to keep in fee wallet. Excess will be transferred to merchant wallet automatically. (Default: 15,000 XEP)' => array('tr'=>'Ücret cüzdanında tutulacak maksimum XEP. Fazlası otomatik olarak satıcı cüzdanına aktarılır. (Varsayılan: 15.000 XEP)','de'=>'Maximales XEP im Gebühren-Wallet. Überschuss wird automatisch übertragen. (Standard: 15.000 XEP)','fr'=>'XEP maximum dans le portefeuille de frais. L\'excédent sera transféré automatiquement. (Par défaut: 15 000 XEP)','es'=>'Máximo XEP en la billetera de comisiones. El exceso se transferirá automáticamente. (Por defecto: 15.000 XEP)','pt'=>'Máximo de XEP na carteira de taxas. O excesso será transferido automaticamente. (Padrão: 15.000 XEP)','it'=>'Massimo XEP nel portafoglio commissioni. L\'eccesso verrà trasferito automaticamente. (Predefinito: 15.000 XEP)','nl'=>'Maximaal XEP in kostenportemonnee. Overschot wordt automatisch overgemaakt. (Standaard: 15.000 XEP)','ru'=>'Максимум XEP в кошельке комиссий. Излишек переводится автоматически. (По умолчанию: 15 000 XEP)','zh'=>'手续费钱包最大持有XEP数量。超出部分将自动转入商户钱包。（默认：15,000 XEP）','ja'=>'手数料ウォレットの最大XEP保持量。超過分は自動的に販売者ウォレットに転送。（デフォルト: 15,000 XEP）','ko'=>'수수료 지갑의 최대 XEP 보유량. 초과분은 자동으로 판매자 지갑으로 이체됩니다. (기본값: 15,000 XEP)','ar'=>'الحد الأقصى لـ XEP في محفظة الرسوم. سيتم تحويل الزيادة تلقائيًا. (الافتراضي: 15,000 XEP)','hi'=>'शुल्क वॉलेट में रखने के लिए अधिकतम XEP। अतिरिक्त स्वचालित रूप से स्थानांतरित। (डिफ़ॉल्ट: 15,000 XEP)','pl'=>'Maksymalny XEP w portfelu opłat. Nadwyżka zostanie automatycznie przeniesiona. (Domyślnie: 15 000 XEP)'),
        'Add tokens one by one. Specify the source (MEXC/CoinGecko/Dex-Trade) and the corresponding ID or pair.' => array('tr'=>'Tokenleri tek tek ekleyin. Kaynağı (MEXC/CoinGecko/Dex-Trade) ve ilgili ID veya çifti belirtin.','de'=>'Token einzeln hinzufügen. Quelle und zugehörige ID oder Paar angeben.','fr'=>'Ajoutez les jetons un par un. Spécifiez la source et l\'ID ou la paire correspondante.','es'=>'Agregue tokens uno por uno. Especifique la fuente y el ID o par correspondiente.','pt'=>'Adicione tokens um por um. Especifique a fonte e o ID ou par correspondente.','it'=>'Aggiungi token uno per uno. Specifica la fonte e l\'ID o la coppia corrispondente.','nl'=>'Voeg tokens één voor één toe. Geef de bron en het bijbehorende ID of paar op.','ru'=>'Добавляйте токены по одному. Укажите источник и соответствующий ID или пару.','zh'=>'逐一添加代币。指定来源和对应的ID或交易对。','ja'=>'トークンを1つずつ追加。ソースと対応するIDまたはペアを指定。','ko'=>'토큰을 하나씩 추가하세요. 소스와 해당 ID 또는 페어를 지정하세요.','ar'=>'أضف الرموز واحدًا تلو الآخر. حدد المصدر والمعرف أو الزوج المقابل.','hi'=>'एक-एक करके टोकन जोड़ें। स्रोत और संबंधित ID या जोड़ी निर्दिष्ट करें।','pl'=>'Dodawaj tokeny pojedynczo. Określ źródło i odpowiedni ID lub parę.'),
        'Status to set the order to after a successful transaction.' => array('tr'=>'Başarılı bir işlem sonrasında siparişe atanacak durum.','de'=>'Status der Bestellung nach erfolgreicher Transaktion.','fr'=>'Statut de la commande après une transaction réussie.','es'=>'Estado del pedido tras una transacción exitosa.','pt'=>'Status do pedido após transação bem-sucedida.','it'=>'Stato dell\'ordine dopo una transazione riuscita.','nl'=>'Bestelstatus na een succesvolle transactie.','ru'=>'Статус заказа после успешной транзакции.','zh'=>'成功交易后设置的订单状态。','ja'=>'取引成功後の注文ステータス。','ko'=>'성공적인 거래 후 주문 상태.','ar'=>'حالة الطلب بعد معاملة ناجحة.','hi'=>'सफल लेनदेन के बाद ऑर्डर की स्थिति।','pl'=>'Status zamówienia po udanej transakcji.'),
        'These details will be used for invoicing service commission fees.' => array('tr'=>'Bu bilgiler hizmet komisyon ücretlerinin faturalandırılması için kullanılacaktır.','de'=>'Diese Angaben werden für die Rechnungsstellung der Provisionsgebühren verwendet.','fr'=>'Ces informations seront utilisées pour la facturation des commissions.','es'=>'Estos datos se usarán para facturar las comisiones de servicio.','pt'=>'Estes dados serão usados para faturar as taxas de comissão.','it'=>'Queste informazioni verranno utilizzate per la fatturazione delle commissioni.','nl'=>'Deze gegevens worden gebruikt voor facturering van commissiekosten.','ru'=>'Эти данные будут использоваться для выставления счетов за комиссии.','zh'=>'这些信息将用于佣金费用的开票。','ja'=>'これらの情報は手数料の請求に使用されます。','ko'=>'이 정보는 수수료 청구서 발행에 사용됩니다.','ar'=>'ستُستخدم هذه التفاصيل لفوترة رسوم العمولة.','hi'=>'इन विवरणों का उपयोग कमीशन शुल्क के चालान के लिए किया जाएगा।','pl'=>'Te dane zostaną użyte do fakturowania prowizji.'),
        'The person or company name for the invoice.' => array('tr'=>'Fatura için kişi veya şirket adı.','de'=>'Name der Person oder Firma für die Rechnung.','fr'=>'Nom de la personne ou de l\'entreprise pour la facture.','es'=>'Nombre de la persona o empresa para la factura.','pt'=>'Nome da pessoa ou empresa para a fatura.','it'=>'Nome della persona o azienda per la fattura.','nl'=>'Naam van de persoon of het bedrijf voor de factuur.','ru'=>'Имя или название компании для счёта.','zh'=>'发票上的个人或公司名称。','ja'=>'請求書用の個人名または会社名。','ko'=>'청구서의 개인 또는 회사 이름.','ar'=>'اسم الشخص أو الشركة للفاتورة.','hi'=>'चालान के लिए व्यक्ति या कंपनी का नाम।','pl'=>'Nazwa osoby lub firmy na fakturze.'),
        'Email address to receive invoices.' => array('tr'=>'Faturaları almak için e-posta adresi.','de'=>'E-Mail-Adresse für den Rechnungsempfang.','fr'=>'Adresse e-mail pour recevoir les factures.','es'=>'Correo electrónico para recibir facturas.','pt'=>'Endereço de e-mail para receber faturas.','it'=>'Indirizzo e-mail per ricevere le fatture.','nl'=>'E-mailadres voor het ontvangen van facturen.','ru'=>'Адрес электронной почты для получения счетов.','zh'=>'接收发票的电子邮件地址。','ja'=>'請求書を受信するメールアドレス。','ko'=>'청구서를 받을 이메일 주소.','ar'=>'عنوان البريد الإلكتروني لاستلام الفواتير.','hi'=>'चालान प्राप्त करने के लिए ईमेल पता।','pl'=>'Adres e-mail do odbioru faktur.'),
        'Your tax identification number or VAT number (optional).' => array('tr'=>'Vergi kimlik numaranız veya KDV numaranız (isteğe bağlı).','de'=>'Ihre Steuer-ID oder USt-IdNr. (optional).','fr'=>'Votre numéro d\'identification fiscale ou TVA (facultatif).','es'=>'Su número de identificación fiscal o IVA (opcional).','pt'=>'Seu número de identificação fiscal ou IVA (opcional).','it'=>'Il codice fiscale o la partita IVA (opzionale).','nl'=>'Uw BTW-nummer (optioneel).','ru'=>'Ваш ИНН или номер НДС (необязательно).','zh'=>'您的税务识别号或增值税号（可选）。','ja'=>'納税者番号またはVAT番号（任意）。','ko'=>'세금 식별 번호 또는 VAT 번호 (선택사항).','ar'=>'رقمك الضريبي أو رقم ضريبة القيمة المضافة (اختياري).','hi'=>'आपका कर पहचान संख्या या वैट नंबर (वैकल्पिक)।','pl'=>'Numer NIP lub VAT (opcjonalnie).'),
        'Is this a personal or business account?' => array('tr'=>'Bu kişisel mi yoksa ticari bir hesap mı?','de'=>'Ist dies ein persönliches oder geschäftliches Konto?','fr'=>'Est-ce un compte personnel ou professionnel?','es'=>'¿Es una cuenta personal o empresarial?','pt'=>'Esta é uma conta pessoal ou empresarial?','it'=>'È un account personale o aziendale?','nl'=>'Is dit een persoonlijk of zakelijk account?','ru'=>'Это личный или бизнес-аккаунт?','zh'=>'这是个人账户还是企业账户？','ja'=>'個人アカウントですか、ビジネスアカウントですか？','ko'=>'개인 계정인가요, 비즈니스 계정인가요?','ar'=>'هل هذا حساب شخصي أم تجاري؟','hi'=>'क्या यह व्यक्तिगत या व्यावसायिक खाता है?','pl'=>'Czy to konto osobiste czy firmowe?'),
        'Country for invoice billing.' => array('tr'=>'Fatura için ülke.','de'=>'Land für die Rechnungsstellung.','fr'=>'Pays pour la facturation.','es'=>'País para facturación.','pt'=>'País para faturação.','it'=>'Paese per la fatturazione.','nl'=>'Land voor facturering.','ru'=>'Страна для выставления счетов.','zh'=>'发票所在国家。','ja'=>'請求先の国。','ko'=>'청구 국가.','ar'=>'البلد للفوترة.','hi'=>'चालान बिलिंग के लिए देश।','pl'=>'Kraj do fakturowania.'),
        'Full address details.' => array('tr'=>'Tam adres bilgileri.','de'=>'Vollständige Adressangaben.','fr'=>'Détails complets de l\'adresse.','es'=>'Detalles completos de la dirección.','pt'=>'Detalhes completos do endereço.','it'=>'Dettagli completi dell\'indirizzo.','nl'=>'Volledige adresgegevens.','ru'=>'Полные данные адреса.','zh'=>'完整地址信息。','ja'=>'住所の詳細。','ko'=>'전체 주소 세부 정보.','ar'=>'تفاصيل العنوان الكامل.','hi'=>'पूर्ण पता विवरण।','pl'=>'Pełne dane adresowe.'),

        // Wallet Generator & Module Status UI
        'Wallet Generator' => array('tr'=>'Cüzdan Oluşturucu','de'=>'Wallet-Generator','fr'=>'Générateur de portefeuille','es'=>'Generador de billetera','pt'=>'Gerador de carteira','it'=>'Generatore portafoglio','nl'=>'Portemonnee-generator','ru'=>'Генератор кошелька','zh'=>'钱包生成器','ja'=>'ウォレット生成','ko'=>'지갑 생성기','ar'=>'مولد المحفظة','hi'=>'वॉलेट जनरेटर','pl'=>'Generator portfela'),
        'Active Module Status' => array('tr'=>'Aktif Modül Durumu','de'=>'Aktiver Modulstatus','fr'=>'Statut du module actif','es'=>'Estado del módulo activo','pt'=>'Status do módulo ativo','it'=>'Stato modulo attivo','nl'=>'Actieve modulestatus','ru'=>'Статус активного модуля','zh'=>'活动模块状态','ja'=>'アクティブモジュール状態','ko'=>'활성 모듈 상태','ar'=>'حالة الوحدة النشطة','hi'=>'सक्रिय मॉड्यूल स्थिति','pl'=>'Status aktywnego modułu'),
        'READY' => array('tr'=>'HAZIR','de'=>'BEREIT','fr'=>'PRÊT','es'=>'LISTO','pt'=>'PRONTO','it'=>'PRONTO','nl'=>'GEREED','ru'=>'ГОТОВ','zh'=>'就绪','ja'=>'準備完了','ko'=>'준비','ar'=>'جاهز','hi'=>'तैयार','pl'=>'GOTOWY'),
        'NOT ACTIVATED' => array('tr'=>'AKTİF DEĞİL','de'=>'NICHT AKTIVIERT','fr'=>'NON ACTIVÉ','es'=>'NO ACTIVADO','pt'=>'NÃO ATIVADO','it'=>'NON ATTIVATO','nl'=>'NIET GEACTIVEERD','ru'=>'НЕ АКТИВИРОВАН','zh'=>'未激活','ja'=>'未アクティブ','ko'=>'활성화되지 않음','ar'=>'غير مفعّل','hi'=>'सक्रिय नहीं','pl'=>'NIEAKTYWOWANY'),
        'GENERATE NEW SECURE WALLET' => array('tr'=>'YENİ GÜVENLİ CÜZDAN OLUŞTUR','de'=>'NEUES SICHERES WALLET ERSTELLEN','fr'=>'GÉNÉRER UN NOUVEAU PORTEFEUILLE','es'=>'GENERAR NUEVA BILLETERA SEGURA','pt'=>'GERAR NOVA CARTEIRA SEGURA','it'=>'GENERA NUOVO PORTAFOGLIO SICURO','nl'=>'NIEUW VEILIG PORTEMONNEE GENEREREN','ru'=>'СОЗДАТЬ НОВЫЙ БЕЗОПАСНЫЙ КОШЕЛЁК','zh'=>'生成新的安全钱包','ja'=>'新しい安全なウォレットを生成','ko'=>'새 보안 지갑 생성','ar'=>'إنشاء محفظة آمنة جديدة','hi'=>'नया सुरक्षित वॉलेट बनाएं','pl'=>'GENERUJ NOWY BEZPIECZNY PORTFEL'),
        'IMPORT EXISTING WALLET' => array('tr'=>'MEVCUT CÜZDANI İÇE AKTAR','de'=>'VORHANDENES WALLET IMPORTIEREN','fr'=>'IMPORTER UN PORTEFEUILLE EXISTANT','es'=>'IMPORTAR BILLETERA EXISTENTE','pt'=>'IMPORTAR CARTEIRA EXISTENTE','it'=>'IMPORTA PORTAFOGLIO ESISTENTE','nl'=>'BESTAAND PORTEMONNEE IMPORTEREN','ru'=>'ИМПОРТИРОВАТЬ СУЩЕСТВУЮЩИЙ КОШЕЛЁК','zh'=>'导入现有钱包','ja'=>'既存のウォレットをインポート','ko'=>'기존 지갑 가져오기','ar'=>'استيراد محفظة موجودة','hi'=>'मौजूदा वॉलेट आयात करें','pl'=>'IMPORTUJ ISTNIEJĄCY PORTFEL'),
        'ACTIVATE MODULE' => array('tr'=>'MODÜLÜ ETKİNLEŞTİR','de'=>'MODUL AKTIVIEREN','fr'=>'ACTIVER LE MODULE','es'=>'ACTIVAR MÓDULO','pt'=>'ATIVAR MÓDULO','it'=>'ATTIVA MODULO','nl'=>'MODULE ACTIVEREN','ru'=>'АКТИВИРОВАТЬ МОДУЛЬ','zh'=>'激活模块','ja'=>'モジュールを有効化','ko'=>'모듈 활성화','ar'=>'تفعيل الوحدة','hi'=>'मॉड्यूल सक्रिय करें','pl'=>'AKTYWUJ MODUŁ'),
        'UPDATE INFO NOW' => array('tr'=>'BİLGİLERİ ŞİMDİ GÜNCELLE','de'=>'INFOS JETZT AKTUALISIEREN','fr'=>'METTRE À JOUR MAINTENANT','es'=>'ACTUALIZAR AHORA','pt'=>'ATUALIZAR AGORA','it'=>'AGGIORNA ORA','nl'=>'NU BIJWERKEN','ru'=>'ОБНОВИТЬ СЕЙЧАС','zh'=>'立即更新信息','ja'=>'今すぐ情報を更新','ko'=>'지금 정보 업데이트','ar'=>'تحديث المعلومات الآن','hi'=>'अभी जानकारी अपडेट करें','pl'=>'AKTUALIZUJ TERAZ'),
        'REFRESH' => array('tr'=>'YENİLE','de'=>'AKTUALISIEREN','fr'=>'ACTUALISER','es'=>'ACTUALIZAR','pt'=>'ATUALIZAR','it'=>'AGGIORNA','nl'=>'VERNIEUWEN','ru'=>'ОБНОВИТЬ','zh'=>'刷新','ja'=>'更新','ko'=>'새로고침','ar'=>'تحديث','hi'=>'रिफ्रेश','pl'=>'ODŚWIEŻ'),
        'BALANCE' => array('tr'=>'BAKİYE','de'=>'GUTHABEN','fr'=>'SOLDE','es'=>'SALDO','pt'=>'SALDO','it'=>'SALDO','nl'=>'SALDO','ru'=>'БАЛАНС','zh'=>'余额','ja'=>'残高','ko'=>'잔고','ar'=>'الرصيد','hi'=>'शेष','pl'=>'SALDO'),
        'NEW WALLET ADDRESS' => array('tr'=>'YENİ CÜZDAN ADRESİ','de'=>'NEUE WALLET-ADRESSE','fr'=>'NOUVELLE ADRESSE','es'=>'NUEVA DIRECCIÓN','pt'=>'NOVO ENDEREÇO','it'=>'NUOVO INDIRIZZO','nl'=>'NIEUW ADRES','ru'=>'НОВЫЙ АДРЕС КОШЕЛЬКА','zh'=>'新钱包地址','ja'=>'新しいウォレットアドレス','ko'=>'새 지갑 주소','ar'=>'عنوان المحفظة الجديد','hi'=>'नया वॉलेट पता','pl'=>'NOWY ADRES PORTFELA'),
        'MNEMONIC SEED (BACKUP NOW)' => array('tr'=>'ANIMSATİCI KELİMELER (ŞİMDİ YEDEKLE)','de'=>'MNEMONISCHE PHRASE (JETZT SICHERN)','fr'=>'PHRASE MNÉMONIQUE (SAUVEGARDER)','es'=>'FRASE MNEMÓNICA (RESPALDAR AHORA)','pt'=>'FRASE MNEMÔNICA (FAZER BACKUP)','it'=>'FRASE MNEMONICA (BACKUP ORA)','nl'=>'MNEMONISCHE ZIN (NU BACK-UPPEN)','ru'=>'МНЕМОНИЧЕСКАЯ ФРАЗА (СДЕЛАЙТЕ РЕЗЕРВНУЮ КОПИЮ)','zh'=>'助记词（立即备份）','ja'=>'ニーモニックシード（今すぐバックアップ）','ko'=>'니모닉 시드 (지금 백업)','ar'=>'الكلمات المفتاحية (قم بالنسخ الاحتياطي الآن)','hi'=>'स्मरणीय शब्द (अभी बैकअप लें)','pl'=>'FRAZA MNEMONICZNA (ZRÓB KOPIĘ)'),
        'SYSTEM FEE FUND BALANCE' => array('tr'=>'SİSTEM ÜCRET FONU BAKİYESİ','de'=>'SYSTEMGEBÜHREN-FONDS','fr'=>'SOLDE DU FONDS DE FRAIS','es'=>'SALDO DEL FONDO DE COMISIONES','pt'=>'SALDO DO FUNDO DE TAXAS','it'=>'SALDO FONDO COMMISSIONI','nl'=>'SYSTEEM KOSTENFONDS SALDO','ru'=>'БАЛАНС ФОНДА СИСТЕМНЫХ КОМИССИЙ','zh'=>'系统手续费基金余额','ja'=>'システム手数料ファンド残高','ko'=>'시스템 수수료 펀드 잔액','ar'=>'رصيد صندوق رسوم النظام','hi'=>'सिस्टम शुल्क निधि शेष','pl'=>'SALDO FUNDUSZU OPŁAT SYSTEMOWYCH'),
        'PENDING COMM.' => array('tr'=>'BEKLEYEN KOMİSYON','de'=>'AUSSTEHENDE PROV.','fr'=>'COMM. EN ATTENTE','es'=>'COM. PENDIENTE','pt'=>'COM. PENDENTE','it'=>'COMM. IN SOSPESO','nl'=>'OPENST. COMM.','ru'=>'ОЖИД. КОМИССИЯ','zh'=>'待处理佣金','ja'=>'保留中の手数料','ko'=>'대기 수수료','ar'=>'العمولة المعلقة','hi'=>'लंबित कमीशन','pl'=>'OCZEK. PROWIZJA'),
        'TOTAL PAID ACC.' => array('tr'=>'TOPLAM ÖDENEN','de'=>'GESAMT BEZAHLT','fr'=>'TOTAL PAYÉ','es'=>'TOTAL PAGADO','pt'=>'TOTAL PAGO','it'=>'TOTALE PAGATO','nl'=>'TOTAAL BETAALD','ru'=>'ВСЕГО ОПЛАЧЕНО','zh'=>'累计已付','ja'=>'累計支払額','ko'=>'총 지불 누적','ar'=>'إجمالي المدفوع','hi'=>'कुल भुगतान','pl'=>'ŁĄCZNIE ZAPŁACONO'),

        // Security warnings
        'CRITICAL SECURITY WARNING:' => array('tr'=>'KRİTİK GÜVENLİK UYARISI:','de'=>'KRITISCHE SICHERHEITSWARNUNG:','fr'=>'AVERTISSEMENT DE SÉCURITÉ CRITIQUE:','es'=>'ADVERTENCIA DE SEGURIDAD CRÍTICA:','pt'=>'AVISO DE SEGURANÇA CRÍTICO:','it'=>'AVVISO DI SICUREZZA CRITICO:','nl'=>'KRITIEKE BEVEILIGINGSWAARSCHUWING:','ru'=>'КРИТИЧЕСКОЕ ПРЕДУПРЕЖДЕНИЕ БЕЗОПАСНОСТИ:','zh'=>'严重安全警告：','ja'=>'重要なセキュリティ警告：','ko'=>'중요 보안 경고:','ar'=>'تحذير أمني حرج:','hi'=>'गंभीर सुरक्षा चेतावनी:','pl'=>'KRYTYCZNE OSTRZEŻENIE BEZPIECZEŃSTWA:'),
        'AUTO-PILOT READY' => array('tr'=>'OTOMATİK PİLOT HAZIR','de'=>'AUTO-PILOT BEREIT','fr'=>'PILOTE AUTOMATIQUE PRÊT','es'=>'PILOTO AUTOMÁTICO LISTO','pt'=>'PILOTO AUTOMÁTICO PRONTO','it'=>'PILOTA AUTOMATICO PRONTO','nl'=>'AUTO-PILOOT GEREED','ru'=>'АВТОПИЛОТ ГОТОВ','zh'=>'自动驾驶就绪','ja'=>'オートパイロット準備完了','ko'=>'자동 결제 준비 완료','ar'=>'الطيار الآلي جاهز','hi'=>'ऑटो-पायलट तैयार','pl'=>'AUTOPILOT GOTOWY'),
        'Auto-Pilot Device Mismatch!' => array('tr'=>'Otomatik Pilot Cihaz Uyumsuzluğu!','de'=>'Auto-Pilot Gerätekonflikt!','fr'=>'Incompatibilité d\'appareil Auto-Pilote!','es'=>'¡Incompatibilidad de dispositivo Auto-Piloto!','pt'=>'Incompatibilidade de dispositivo Auto-Piloto!','it'=>'Disallineamento dispositivo Auto-Pilota!','nl'=>'Auto-Piloot apparaat mismatch!','ru'=>'Несоответствие устройства Автопилота!','zh'=>'自动驾驶设备不匹配！','ja'=>'オートパイロット デバイス不一致！','ko'=>'자동 결제 장치 불일치!','ar'=>'عدم تطابق جهاز الطيار الآلي!','hi'=>'ऑटो-पायलट डिवाइस बेमेल!','pl'=>'Niezgodność urządzenia Autopilota!'),
        'SERVICE & COMMISSION POLICY:' => array('tr'=>'HİZMET VE KOMİSYON POLİTİKASI:','de'=>'SERVICE- & PROVISIONSRICHTLINIE:','fr'=>'POLITIQUE DE SERVICE & COMMISSION:','es'=>'POLÍTICA DE SERVICIO Y COMISIÓN:','pt'=>'POLÍTICA DE SERVIÇO E COMISSÃO:','it'=>'POLITICA SERVIZIO E COMMISSIONE:','nl'=>'SERVICE- & COMMISSIEBELEID:','ru'=>'ПОЛИТИКА ОБСЛУЖИВАНИЯ И КОМИССИЙ:','zh'=>'服务与佣金政策：','ja'=>'サービス＆手数料ポリシー：','ko'=>'서비스 및 수수료 정책:','ar'=>'سياسة الخدمة والعمولة:','hi'=>'सेवा और कमीशन नीति:','pl'=>'POLITYKA USŁUG I PROWIZJI:'),
        'Backup these mnemonic words to a safe place NOW!' => array('tr'=>'Anımsatıcı kelimeleri ŞİMDİ güvenli bir yere yedekleyin!','de'=>'Sichern Sie die mnemonischen Wörter JETZT an einem sicheren Ort!','fr'=>'Sauvegardez ces mots mnémoniques dans un endroit sûr MAINTENANT!','es'=>'¡Respalde estas palabras mnemónicas en un lugar seguro AHORA!','pt'=>'Faça backup das palavras mnemônicas em um local seguro AGORA!','it'=>'Effettua il backup delle parole mnemoniche in un luogo sicuro ORA!','nl'=>'Maak NU een back-up van de mnemonische woorden!','ru'=>'Сохраните мнемонические слова в безопасном месте СЕЙЧАС!','zh'=>'立即将助记词备份到安全的地方！','ja'=>'ニーモニックワードを今すぐ安全な場所にバックアップしてください！','ko'=>'니모닉 단어를 지금 안전한 곳에 백업하세요!','ar'=>'قم بنسخ الكلمات المفتاحية احتياطيًا في مكان آمن الآن!','hi'=>'स्मरणीय शब्दों का अभी सुरक्षित स्थान पर बैकअप लें!','pl'=>'Wykonaj kopię zapasową słów mnemonicznych TERAZ!'),
        'NEVER share them with anyone' => array('tr'=>'Bunları KİMSEYLE paylaşmayın','de'=>'Teilen Sie sie NIEMALS mit anderen','fr'=>'Ne les partagez JAMAIS avec quiconque','es'=>'NUNCA los comparta con nadie','pt'=>'NUNCA os compartilhe com ninguém','it'=>'NON condividerle MAI con nessuno','nl'=>'Deel ze NOOIT met iemand','ru'=>'НИКОГДА не делитесь ими','zh'=>'绝对不要与任何人分享','ja'=>'絶対に他人と共有しないでください','ko'=>'절대 다른 사람과 공유하지 마세요','ar'=>'لا تشاركها مع أي شخص أبدًا','hi'=>'इन्हें कभी किसी के साथ साझा न करें','pl'=>'NIGDY ich nikomu nie udostępniaj'),
        'Once ACTIVATE MODULE is clicked, your keys are encrypted and stored ONLY in THIS browser\'s LocalStorage!' => array('tr'=>'MODÜLÜ ETKİNLEŞTİR tıklandığında anahtarlarınız şifrelenir ve YALNIZCA BU tarayıcının LocalStorage\'ında saklanır!','de'=>'Nach Klick auf MODUL AKTIVIEREN werden Ihre Schlüssel verschlüsselt und NUR im LocalStorage DIESES Browsers gespeichert!','fr'=>'Une fois ACTIVER LE MODULE cliqué, vos clés sont chiffrées et stockées UNIQUEMENT dans le LocalStorage de CE navigateur!','es'=>'Al hacer clic en ACTIVAR MÓDULO, sus claves se cifran y almacenan SOLO en el LocalStorage de ESTE navegador!','pt'=>'Ao clicar em ATIVAR MÓDULO, suas chaves são criptografadas e armazenadas APENAS no LocalStorage DESTE navegador!','it'=>'Cliccando ATTIVA MODULO, le chiavi vengono crittografate e memorizzate SOLO nel LocalStorage di QUESTO browser!','nl'=>'Na klikken op MODULE ACTIVEREN worden uw sleutels versleuteld en ALLEEN opgeslagen in de LocalStorage van DEZE browser!','ru'=>'После нажатия АКТИВИРОВАТЬ МОДУЛЬ ваши ключи шифруются и сохраняются ТОЛЬКО в LocalStorage ЭТОГО браузера!','zh'=>'点击激活模块后，您的密钥将被加密并仅存储在此浏览器的LocalStorage中！','ja'=>'モジュール有効化をクリックすると、キーは暗号化されこのブラウザのLocalStorageにのみ保存されます！','ko'=>'모듈 활성화를 클릭하면 키가 암호화되어 이 브라우저의 LocalStorage에만 저장됩니다!','ar'=>'بمجرد النقر على تفعيل الوحدة، يتم تشفير مفاتيحك وتخزينها فقط في LocalStorage لهذا المتصفح!','hi'=>'मॉड्यूल सक्रिय करें पर क्लिक करने के बाद आपकी कुंजियाँ एन्क्रिप्ट होकर केवल इस ब्राउज़र के LocalStorage में संग्रहीत होती हैं!','pl'=>'Po kliknięciu AKTYWUJ MODUŁ klucze zostaną zaszyfrowane i zapisane TYLKO w LocalStorage TEJ przeglądarki!'),
        'The server never sees your 12 words. If you clear cookies or use a different device, you must re-import.' => array('tr'=>'Sunucu 12 kelimenizi asla görmez. Çerezleri temizlerseniz veya farklı bir cihaz kullanırsanız yeniden içe aktarmalısınız.','de'=>'Der Server sieht Ihre 12 Wörter nie. Bei Cookie-Löschung oder Gerätewechsel müssen Sie erneut importieren.','fr'=>'Le serveur ne voit jamais vos 12 mots. Si vous effacez les cookies ou changez d\'appareil, vous devez réimporter.','es'=>'El servidor nunca ve sus 12 palabras. Si borra cookies o usa otro dispositivo, debe reimportar.','pt'=>'O servidor nunca vê suas 12 palavras. Se limpar cookies ou usar outro dispositivo, deve reimportar.','it'=>'Il server non vede mai le tue 12 parole. Se cancelli i cookie o usi un altro dispositivo, devi reimportare.','nl'=>'De server ziet uw 12 woorden nooit. Bij het wissen van cookies of gebruik van een ander apparaat moet u opnieuw importeren.','ru'=>'Сервер никогда не видит ваши 12 слов. При очистке cookies или смене устройства необходим повторный импорт.','zh'=>'服务器永远不会看到您的12个单词。如果清除cookie或使用其他设备，必须重新导入。','ja'=>'サーバーは12単語を見ることはありません。Cookieを削除したり別のデバイスを使用する場合は再インポートが必要です。','ko'=>'서버는 12개의 단어를 볼 수 없습니다. 쿠키를 삭제하거나 다른 기기를 사용하면 다시 가져와야 합니다.','ar'=>'الخادم لا يرى كلماتك الـ 12 أبدًا. إذا مسحت ملفات تعريف الارتباط أو استخدمت جهازًا آخر، يجب إعادة الاستيراد.','hi'=>'सर्वर आपके 12 शब्दों को कभी नहीं देखता। यदि आप कुकीज़ साफ़ करते हैं या कोई अन्य डिवाइस उपयोग करते हैं, तो पुनः आयात करना होगा।','pl'=>'Serwer nigdy nie widzi twoich 12 słów. Po wyczyszczeniu cookies lub zmianie urządzenia musisz ponownie zaimportować.'),
        'Your keys are encrypted in this browser with AES-256-CBC. Commissions will be processed automatically from this device.' => array('tr'=>'Anahtarlarınız bu tarayıcıda AES-256-CBC ile şifrelenir. Komisyonlar bu cihazdan otomatik olarak işlenir.','de'=>'Ihre Schlüssel sind in diesem Browser mit AES-256-CBC verschlüsselt. Provisionen werden automatisch von diesem Gerät verarbeitet.','fr'=>'Vos clés sont chiffrées dans ce navigateur avec AES-256-CBC. Les commissions seront traitées automatiquement depuis cet appareil.','es'=>'Sus claves están cifradas en este navegador con AES-256-CBC. Las comisiones se procesarán automáticamente desde este dispositivo.','pt'=>'Suas chaves são criptografadas neste navegador com AES-256-CBC. As comissões serão processadas automaticamente deste dispositivo.','it'=>'Le tue chiavi sono crittografate in questo browser con AES-256-CBC. Le commissioni verranno elaborate automaticamente da questo dispositivo.','nl'=>'Uw sleutels zijn versleuteld in deze browser met AES-256-CBC. Commissies worden automatisch verwerkt vanaf dit apparaat.','ru'=>'Ваши ключи зашифрованы в этом браузере с помощью AES-256-CBC. Комиссии будут обрабатываться автоматически с этого устройства.','zh'=>'您的密钥在此浏览器中使用AES-256-CBC加密。佣金将从此设备自动处理。','ja'=>'AES-256-CBCでこのブラウザで暗号化されています。手数料はこのデバイスから自動的に処理されます。','ko'=>'키는 이 브라우저에서 AES-256-CBC로 암호화됩니다. 수수료는 이 기기에서 자동으로 처리됩니다.','ar'=>'مفاتيحك مشفرة في هذا المتصفح بـ AES-256-CBC. ستتم معالجة العمولات تلقائيًا من هذا الجهاز.','hi'=>'आपकी कुंजियाँ इस ब्राउज़र में AES-256-CBC से एन्क्रिप्ट हैं। कमीशन इस डिवाइस से स्वचालित रूप से संसाधित होंगे।','pl'=>'Twoje klucze są zaszyfrowane w tej przeglądarce za pomocą AES-256-CBC. Prowizje będą przetwarzane automatycznie z tego urządzenia.'),
        'This browser is NOT authorized to process commissions. Fee payments are bound to the device where the mnemonic was first entered.' => array('tr'=>'Bu tarayıcı komisyon işlemeye YETKİLİ DEĞİLDİR. Ücret ödemeleri, anımsatıcı kelimelerin ilk girildiği cihaza bağlıdır.','de'=>'Dieser Browser ist NICHT autorisiert, Provisionen zu verarbeiten. Gebührenzahlungen sind an das Gerät gebunden, auf dem die Mnemonik zuerst eingegeben wurde.','fr'=>'Ce navigateur n\'est PAS autorisé à traiter les commissions. Les paiements de frais sont liés à l\'appareil où le mnémonique a été saisi.','es'=>'Este navegador NO está autorizado para procesar comisiones. Los pagos de comisiones están vinculados al dispositivo donde se ingresó el mnemónico.','pt'=>'Este navegador NÃO está autorizado a processar comissões. Os pagamentos de taxas estão vinculados ao dispositivo onde o mnemônico foi inserido.','it'=>'Questo browser NON è autorizzato a elaborare commissioni. I pagamenti sono legati al dispositivo dove è stato inserito il mnemonico.','nl'=>'Deze browser is NIET geautoriseerd om commissies te verwerken. Betalingen zijn gebonden aan het apparaat waar de mnemonische zin is ingevoerd.','ru'=>'Этот браузер НЕ авторизован для обработки комиссий. Платежи привязаны к устройству, на котором была введена мнемоника.','zh'=>'此浏览器未被授权处理佣金。费用支付绑定到首次输入助记词的设备。','ja'=>'このブラウザは手数料処理の権限がありません。手数料支払いはニーモニックが最初に入力されたデバイスに紐付けられています。','ko'=>'이 브라우저는 수수료 처리 권한이 없습니다. 수수료 결제는 니모닉이 처음 입력된 기기에 연결되어 있습니다.','ar'=>'هذا المتصفح غير مصرح له بمعالجة العمولات. مدفوعات الرسوم مرتبطة بالجهاز الذي تم إدخال الكلمات المفتاحية فيه أولاً.','hi'=>'यह ब्राउज़र कमीशन प्रोसेस करने के लिए अधिकृत नहीं है। शुल्क भुगतान उस डिवाइस से जुड़े हैं जहाँ स्मरणीय शब्द पहली बार दर्ज किए गए थे।','pl'=>'Ta przeglądarka NIE jest autoryzowana do przetwarzania prowizji. Płatności są powiązane z urządzeniem, na którym wprowadzono mnemonik.'),
        'If you want to use THIS device for automatic payments, you MUST re-import your 12-word mnemonic in the "Import Existing Wallet" section.' => array('tr'=>'Bu cihazı otomatik ödemeler için kullanmak istiyorsanız, 12 kelimelik anımsatıcınızı "Mevcut Cüzdanı İçe Aktar" bölümünden yeniden içe aktarmalısınız.','de'=>'Wenn Sie DIESES Gerät für automatische Zahlungen verwenden möchten, MÜSSEN Sie Ihre 12-Wort-Mnemonik im Abschnitt "Vorhandenes Wallet importieren" erneut importieren.','fr'=>'Si vous souhaitez utiliser CET appareil pour les paiements automatiques, vous DEVEZ réimporter votre mnémonique de 12 mots dans la section "Importer un portefeuille existant".','es'=>'Si desea usar ESTE dispositivo para pagos automáticos, DEBE reimportar su mnemónico de 12 palabras en la sección "Importar billetera existente".','pt'=>'Se quiser usar ESTE dispositivo para pagamentos automáticos, DEVE reimportar seu mnemônico de 12 palavras na seção "Importar carteira existente".','it'=>'Se vuoi usare QUESTO dispositivo per i pagamenti automatici, DEVI reimportare il tuo mnemonico di 12 parole nella sezione "Importa portafoglio esistente".','nl'=>'Als u DIT apparaat wilt gebruiken voor automatische betalingen, MOET u uw 12-woordige mnemonische zin opnieuw importeren in het gedeelte "Bestaand portemonnee importeren".','ru'=>'Если вы хотите использовать ЭТО устройство для автоматических платежей, вы ДОЛЖНЫ повторно импортировать вашу 12-словную мнемонику в разделе "Импортировать существующий кошелёк".','zh'=>'如果您想使用此设备进行自动付款，必须在"导入现有钱包"部分重新导入您的12个助记词。','ja'=>'このデバイスで自動支払いを使用するには、「既存のウォレットをインポート」セクションで12単語のニーモニックを再インポートする必要があります。','ko'=>'이 기기에서 자동 결제를 사용하려면 "기존 지갑 가져오기" 섹션에서 12개의 니모닉 단어를 다시 가져와야 합니다.','ar'=>'إذا كنت تريد استخدام هذا الجهاز للمدفوعات التلقائية، يجب إعادة استيراد الكلمات المفتاحية الـ 12 في قسم "استيراد محفظة موجودة".','hi'=>'यदि आप इस डिवाइस को स्वचालित भुगतान के लिए उपयोग करना चाहते हैं, तो आपको "मौजूदा वॉलेट आयात करें" अनुभाग में अपने 12-शब्द के स्मरणीय शब्दों को पुनः आयात करना होगा।','pl'=>'Jeśli chcesz używać TEGO urządzenia do automatycznych płatności, MUSISZ ponownie zaimportować swój 12-wyrazowy mnemonik w sekcji "Importuj istniejący portfel".'),
        'Failure to settle commissions will eventually lead to the deactivation of your OmniXEP Payment Gateway.' => array('tr'=>'Komisyonların ödenmemesi sonunda OmniXEP Ödeme Ağ Geçidinizin devre dışı bırakılmasına yol açacaktır.','de'=>'Die Nichtbegleichung von Provisionen führt letztendlich zur Deaktivierung Ihres OmniXEP Payment Gateways.','fr'=>'Le non-règlement des commissions entraînera la désactivation de votre passerelle de paiement OmniXEP.','es'=>'No liquidar las comisiones eventualmente llevará a la desactivación de su pasarela de pago OmniXEP.','pt'=>'A falha em liquidar comissões levará à desativação do seu Gateway de Pagamento OmniXEP.','it'=>'Il mancato pagamento delle commissioni porterà alla disattivazione del tuo OmniXEP Payment Gateway.','nl'=>'Het niet afhandelen van commissies leidt uiteindelijk tot deactivering van uw OmniXEP Payment Gateway.','ru'=>'Неуплата комиссий приведёт к деактивации вашего платёжного шлюза OmniXEP.','zh'=>'未能结算佣金将最终导致您的OmniXEP支付网关被停用。','ja'=>'手数料の未払いは最終的にOmniXEP決済ゲートウェイの無効化につながります。','ko'=>'수수료를 정산하지 않으면 OmniXEP 결제 게이트웨이가 비활성화됩니다.','ar'=>'عدم تسوية العمولات سيؤدي في النهاية إلى تعطيل بوابة الدفع OmniXEP الخاصة بك.','hi'=>'कमीशन का भुगतान न करने पर अंततः आपके OmniXEP भुगतान गेटवे को निष्क्रिय कर दिया जाएगा।','pl'=>'Brak rozliczenia prowizji ostatecznie doprowadzi do dezaktywacji bramki płatności OmniXEP.'),
        'A 0.8% sales commission is collected automatically from this Fee Wallet (as XEP). Always maintain 10,000 XEP+ in the funding wallet to ensure uninterrupted merchant service.' => array('tr'=>'Bu Ücret Cüzdanından otomatik olarak %0.8 satış komisyonu tahsil edilir (XEP olarak). Kesintisiz satıcı hizmeti sağlamak için fonlama cüzdanında her zaman 10.000 XEP+ bulundurun.','de'=>'Eine 0,8% Verkaufsprovision wird automatisch aus diesem Gebühren-Wallet (als XEP) erhoben. Halten Sie immer 10.000 XEP+ im Funding-Wallet für unterbrechungsfreien Service.','fr'=>'Une commission de 0,8% est collectée automatiquement depuis ce portefeuille de frais (en XEP). Maintenez toujours 10 000 XEP+ pour un service continu.','es'=>'Se cobra automáticamente una comisión del 0,8% de esta billetera de comisiones (como XEP). Mantenga siempre 10.000 XEP+ para un servicio ininterrumpido.','pt'=>'Uma comissão de 0,8% é coletada automaticamente desta carteira de taxas (como XEP). Mantenha sempre 10.000 XEP+ para serviço ininterrupto.','it'=>'Una commissione dello 0,8% viene raccolta automaticamente da questo portafoglio commissioni (come XEP). Mantieni sempre 10.000 XEP+ per un servizio ininterrotto.','nl'=>'Een verkoopcommissie van 0,8% wordt automatisch geïnd uit deze kostenportemonnee (als XEP). Houd altijd 10.000 XEP+ aan voor ononderbroken service.','ru'=>'Комиссия 0,8% от продаж автоматически списывается из этого кошелька комиссий (в XEP). Всегда поддерживайте 10 000 XEP+ для бесперебойного обслуживания.','zh'=>'0.8%的销售佣金将从此手续费钱包中自动收取（以XEP计）。请始终保持10,000 XEP+以确保商户服务不中断。','ja'=>'0.8%の販売手数料がこの手数料ウォレットから自動的に徴収されます（XEP建て）。中断のないサービスのため常に10,000 XEP以上を維持してください。','ko'=>'0.8%의 판매 수수료가 이 수수료 지갑에서 자동으로 징수됩니다(XEP). 중단 없는 서비스를 위해 항상 10,000 XEP 이상을 유지하세요.','ar'=>'يتم تحصيل عمولة مبيعات بنسبة 0.8% تلقائيًا من محفظة الرسوم هذه (بـ XEP). حافظ دائمًا على 10,000 XEP+ لضمان خدمة مستمرة.','hi'=>'इस शुल्क वॉलेट से 0.8% बिक्री कमीशन स्वचालित रूप से एकत्र किया जाता है (XEP के रूप में)। निर्बाध सेवा के लिए हमेशा 10,000 XEP+ बनाए रखें।','pl'=>'Prowizja 0,8% od sprzedaży jest automatycznie pobierana z tego portfela opłat (jako XEP). Utrzymuj zawsze 10 000 XEP+ dla nieprzerwanej usługi.'),

        // Checkout - Customer Facing
        'SECURE PAYMENT SYSTEM' => array('tr'=>'GÜVENLİ ÖDEME SİSTEMİ','de'=>'SICHERES ZAHLUNGSSYSTEM','fr'=>'SYSTÈME DE PAIEMENT SÉCURISÉ','es'=>'SISTEMA DE PAGO SEGURO','pt'=>'SISTEMA DE PAGAMENTO SEGURO','it'=>'SISTEMA DI PAGAMENTO SICURO','nl'=>'VEILIG BETALINGSSYSTEEM','ru'=>'БЕЗОПАСНАЯ ПЛАТЁЖНАЯ СИСТЕМА','zh'=>'安全支付系统','ja'=>'セキュア決済システム','ko'=>'안전 결제 시스템','ar'=>'نظام دفع آمن','hi'=>'सुरक्षित भुगतान प्रणाली','pl'=>'BEZPIECZNY SYSTEM PŁATNOŚCI'),
        'Pay for your order securely, do not leave the screen until your order is created.' => array('tr'=>'Siparişinizi güvenle ödeyin, sipariş oluşturulana kadar ekrandan ayrılmayın.','de'=>'Bezahlen Sie sicher. Verlassen Sie den Bildschirm nicht, bis die Bestellung erstellt ist.','fr'=>'Payez votre commande en toute sécurité, ne quittez pas l\'écran.','es'=>'Pague su pedido de forma segura, no abandone la pantalla.','pt'=>'Pague com segurança, não saia da tela até o pedido ser criado.','it'=>'Paga in sicurezza, non lasciare lo schermo fino alla creazione dell\'ordine.','nl'=>'Betaal veilig, verlaat het scherm niet tot uw bestelling is aangemaakt.','ru'=>'Оплатите заказ безопасно, не покидайте страницу.','zh'=>'安全支付，订单创建前请勿离开页面。','ja'=>'安全に決済します。注文が作成されるまで画面を離れないでください。','ko'=>'안전하게 결제하세요. 주문이 생성될 때까지 화면을 떠나지 마세요.','ar'=>'ادفع بأمان، لا تغادر الشاشة حتى يتم إنشاء طلبك.','hi'=>'सुरक्षित रूप से भुगतान करें, ऑर्डर बनने तक स्क्रीन न छोड़ें।','pl'=>'Zapłać bezpiecznie, nie opuszczaj ekranu do utworzenia zamówienia.'),
        'Please wait until your order is created...' => array('tr'=>'Siparişiniz oluşturulana kadar lütfen bekleyin...','de'=>'Bitte warten Sie, bis Ihre Bestellung erstellt wird...','fr'=>'Veuillez patienter pendant la création de votre commande...','es'=>'Espere mientras se crea su pedido...','pt'=>'Aguarde enquanto seu pedido é criado...','it'=>'Attendere la creazione dell\'ordine...','nl'=>'Even geduld, uw bestelling wordt aangemaakt...','ru'=>'Пожалуйста, подождите, заказ создаётся...','zh'=>'请等待订单创建...','ja'=>'注文を作成しています。お待ちください...','ko'=>'주문이 생성될 때까지 기다려주세요...','ar'=>'يرجى الانتظار حتى يتم إنشاء طلبك...','hi'=>'कृपया प्रतीक्षा करें, आपका ऑर्डर बनाया जा रहा है...','pl'=>'Proszę czekać, zamówienie jest tworzone...'),
        'Exchange rate is fixed for 30 seconds. It will be updated when the time expires.' => array('tr'=>'Döviz kuru 30 saniye sabitlenir. Süre dolduğunda güncellenecektir.','de'=>'Der Wechselkurs ist 30 Sekunden gültig und wird dann aktualisiert.','fr'=>'Le taux de change est fixé pour 30 secondes puis sera mis à jour.','es'=>'El tipo de cambio se fija por 30 segundos y se actualizará al expirar.','pt'=>'A taxa de câmbio é fixada por 30 segundos e será atualizada ao expirar.','it'=>'Il tasso di cambio è fisso per 30 secondi e verrà aggiornato alla scadenza.','nl'=>'De wisselkoers is 30 seconden vast en wordt daarna bijgewerkt.','ru'=>'Курс зафиксирован на 30 секунд и будет обновлён после истечения.','zh'=>'汇率固定30秒，到期后将更新。','ja'=>'為替レートは30秒固定され、期限切れ時に更新されます。','ko'=>'환율은 30초간 고정되며, 만료 시 갱신됩니다.','ar'=>'سعر الصرف ثابت لمدة 30 ثانية وسيتم تحديثه عند انتهاء المدة.','hi'=>'विनिमय दर 30 सेकंड के लिए तय है। समय समाप्त होने पर अपडेट होगी।','pl'=>'Kurs wymiany jest stały przez 30 sekund i zostanie zaktualizowany po upływie czasu.'),
        'Preferred Token' => array('tr'=>'Tercih Edilen Token','de'=>'Bevorzugter Token','fr'=>'Jeton préféré','es'=>'Token preferido','pt'=>'Token preferido','it'=>'Token preferito','nl'=>'Voorkeurs-token','ru'=>'Предпочтительный токен','zh'=>'首选代币','ja'=>'優先トークン','ko'=>'선호 토큰','ar'=>'الرمز المفضل','hi'=>'पसंदीदा टोकन','pl'=>'Preferowany token'),
        'Select Token' => array('tr'=>'Token Seçin','de'=>'Token wählen','fr'=>'Choisir un jeton','es'=>'Seleccionar token','pt'=>'Selecionar token','it'=>'Seleziona token','nl'=>'Token selecteren','ru'=>'Выберите токен','zh'=>'选择代币','ja'=>'トークンを選択','ko'=>'토큰 선택','ar'=>'اختر الرمز','hi'=>'टोकन चुनें','pl'=>'Wybierz token'),
        'Secure Web3 payment powered by OmniXEP Core.' => array('tr'=>'OmniXEP Core tarafından desteklenen güvenli Web3 ödemesi.','de'=>'Sichere Web3-Zahlung powered by OmniXEP Core.','fr'=>'Paiement Web3 sécurisé par OmniXEP Core.','es'=>'Pago Web3 seguro con OmniXEP Core.','pt'=>'Pagamento Web3 seguro com OmniXEP Core.','it'=>'Pagamento Web3 sicuro con OmniXEP Core.','nl'=>'Veilige Web3-betaling door OmniXEP Core.','ru'=>'Безопасный Web3-платёж на OmniXEP Core.','zh'=>'OmniXEP Core提供的安全Web3支付。','ja'=>'OmniXEP Core対応の安全なWeb3決済。','ko'=>'OmniXEP Core의 안전한 Web3 결제.','ar'=>'دفع Web3 آمن مدعوم من OmniXEP Core.','hi'=>'OmniXEP Core द्वारा संचालित सुरक्षित Web3 भुगतान।','pl'=>'Bezpieczna płatność Web3 przez OmniXEP Core.'),

        // Receipt Page
        'PAYMENT AMOUNT' => array('tr'=>'ÖDEME TUTARI','de'=>'ZAHLUNGSBETRAG','fr'=>'MONTANT DU PAIEMENT','es'=>'MONTO DEL PAGO','pt'=>'VALOR DO PAGAMENTO','it'=>'IMPORTO DEL PAGAMENTO','nl'=>'BETALINGSBEDRAG','ru'=>'СУММА ОПЛАТЫ','zh'=>'支付金额','ja'=>'支払い金額','ko'=>'결제 금액','ar'=>'مبلغ الدفع','hi'=>'भुगतान राशि','pl'=>'KWOTA PŁATNOŚCI'),
        'PAY WITH OMNIXEP WALLET' => array('tr'=>'OMNIXEP CÜZDAN İLE ÖDE','de'=>'MIT OMNIXEP WALLET BEZAHLEN','fr'=>'PAYER AVEC OMNIXEP WALLET','es'=>'PAGAR CON OMNIXEP WALLET','pt'=>'PAGAR COM OMNIXEP WALLET','it'=>'PAGA CON OMNIXEP WALLET','nl'=>'BETAAL MET OMNIXEP WALLET','ru'=>'ОПЛАТИТЬ ЧЕРЕЗ OMNIXEP WALLET','zh'=>'使用OMNIXEP钱包支付','ja'=>'OMNIXEP WALLETで支払う','ko'=>'OMNIXEP 지갑으로 결제','ar'=>'ادفع بمحفظة OMNIXEP','hi'=>'OMNIXEP वॉलेट से भुगतान करें','pl'=>'ZAPŁAĆ PORTFELEM OMNIXEP'),
        'PAY WITH BROWSER WALLET' => array('tr'=>'TARAYICI CÜZDAN İLE ÖDE','de'=>'MIT BROWSER-WALLET BEZAHLEN','fr'=>'PAYER AVEC WALLET NAVIGATEUR','es'=>'PAGAR CON WALLET DEL NAVEGADOR','pt'=>'PAGAR COM WALLET DO NAVEGADOR','it'=>'PAGA CON WALLET DEL BROWSER','nl'=>'BETAAL MET BROWSER-WALLET','ru'=>'ОПЛАТИТЬ ЧЕРЕЗ БРАУЗЕРНЫЙ КОШЕЛЁК','zh'=>'使用浏览器钱包支付','ja'=>'ブラウザウォレットで支払う','ko'=>'브라우저 지갑으로 결제','ar'=>'ادفع بمحفظة المتصفح','hi'=>'ब्राउज़र वॉलेट से भुगतान करें','pl'=>'ZAPŁAĆ PORTFELEM PRZEGLĄDARKI'),
        'Waiting for payment...' => array('tr'=>'Ödeme bekleniyor...','de'=>'Warte auf Zahlung...','fr'=>'En attente du paiement...','es'=>'Esperando el pago...','pt'=>'Aguardando pagamento...','it'=>'In attesa del pagamento...','nl'=>'Wachten op betaling...','ru'=>'Ожидание оплаты...','zh'=>'等待支付...','ja'=>'支払い待ち...','ko'=>'결제 대기 중...','ar'=>'في انتظار الدفع...','hi'=>'भुगतान की प्रतीक्षा...','pl'=>'Oczekiwanie na płatność...'),
        'After paying in the wallet, you\'ll be redirected automatically.' => array('tr'=>'Cüzdandan ödeme yaptıktan sonra otomatik olarak yönlendirileceksiniz.','de'=>'Nach der Zahlung werden Sie automatisch weitergeleitet.','fr'=>'Après le paiement, vous serez redirigé automatiquement.','es'=>'Después de pagar, será redirigido automáticamente.','pt'=>'Após o pagamento, você será redirecionado automaticamente.','it'=>'Dopo il pagamento, verrai reindirizzato automaticamente.','nl'=>'Na betaling wordt u automatisch doorgestuurd.','ru'=>'После оплаты вы будете перенаправлены автоматически.','zh'=>'钱包支付后将自动跳转。','ja'=>'支払い後、自動的にリダイレクトされます。','ko'=>'지갑에서 결제 후 자동으로 리다이렉트됩니다.','ar'=>'بعد الدفع ستتم إعادة توجيهك تلقائيًا.','hi'=>'वॉलेट में भुगतान के बाद आपको स्वचालित रूप से रीडायरेक्ट किया जाएगा।','pl'=>'Po zapłaceniu zostaniesz automatycznie przekierowany.'),
        'Secure payment via Electra Protocol blockchain' => array('tr'=>'Electra Protocol blok zinciri ile güvenli ödeme','de'=>'Sichere Zahlung über die Electra Protocol Blockchain','fr'=>'Paiement sécurisé via la blockchain Electra Protocol','es'=>'Pago seguro a través de Electra Protocol','pt'=>'Pagamento seguro via blockchain Electra Protocol','it'=>'Pagamento sicuro tramite Electra Protocol','nl'=>'Veilige betaling via Electra Protocol','ru'=>'Безопасный платёж через Electra Protocol','zh'=>'通过Electra Protocol区块链安全支付','ja'=>'Electra Protocolブロックチェーンによる安全な決済','ko'=>'Electra Protocol 블록체인을 통한 안전한 결제','ar'=>'دفع آمن عبر بلوكتشين Electra Protocol','hi'=>'Electra Protocol ब्लॉकचेन के माध्यम से सुरक्षित भुगतान','pl'=>'Bezpieczna płatność przez Electra Protocol'),
        'Estimated Total' => array('tr'=>'Tahmini Toplam','de'=>'Geschätzte Summe','fr'=>'Total estimé','es'=>'Total estimado','pt'=>'Total estimado','it'=>'Totale stimato','nl'=>'Geschat totaal','ru'=>'Примерный итог','zh'=>'预估总额','ja'=>'見積り合計','ko'=>'예상 합계','ar'=>'الإجمالي التقديري','hi'=>'अनुमानित कुल','pl'=>'Szacunkowa suma'),
        'Scan with OmniXEP Mobile or any XEP Wallet' => array('tr'=>'OmniXEP Mobile veya herhangi bir XEP Cüzdanı ile tarayın','de'=>'Scannen Sie mit OmniXEP Mobile oder einem XEP-Wallet','fr'=>'Scannez avec OmniXEP Mobile ou tout portefeuille XEP','es'=>'Escanee con OmniXEP Mobile o cualquier billetera XEP','pt'=>'Escaneie com OmniXEP Mobile ou qualquer carteira XEP','it'=>'Scansiona con OmniXEP Mobile o qualsiasi portafoglio XEP','nl'=>'Scan met OmniXEP Mobile of een XEP-wallet','ru'=>'Сканируйте через OmniXEP Mobile или любой XEP кошелёк','zh'=>'使用OmniXEP Mobile或任何XEP钱包扫描','ja'=>'OmniXEP MobileまたはXEPウォレットでスキャン','ko'=>'OmniXEP Mobile 또는 XEP 지갑으로 스캔','ar'=>'امسح باستخدام OmniXEP Mobile أو أي محفظة XEP','hi'=>'OmniXEP Mobile या किसी XEP वॉलेट से स्कैन करें','pl'=>'Zeskanuj za pomocą OmniXEP Mobile lub portfela XEP'),
        'SELECT PAYMENT ASSET' => array('tr'=>'ÖDEME VARLIĞI SEÇİN','de'=>'ZAHLUNGSMITTEL WÄHLEN','fr'=>'CHOISIR L\'ACTIF DE PAIEMENT','es'=>'SELECCIONAR ACTIVO DE PAGO','pt'=>'SELECIONAR ATIVO DE PAGAMENTO','it'=>'SELEZIONA ASSET DI PAGAMENTO','nl'=>'SELECTEER BETAALMIDDEL','ru'=>'ВЫБЕРИТЕ ПЛАТЁЖНЫЙ АКТИВ','zh'=>'选择支付资产','ja'=>'支払い資産を選択','ko'=>'결제 자산 선택','ar'=>'اختر أصل الدفع','hi'=>'भुगतान संपत्ति चुनें','pl'=>'WYBIERZ AKTYWO PŁATNICZE'),
        'PAYMENT STATUS' => array('tr'=>'ÖDEME DURUMU','de'=>'ZAHLUNGSSTATUS','fr'=>'STATUT DU PAIEMENT','es'=>'ESTADO DEL PAGO','pt'=>'STATUS DO PAGAMENTO','it'=>'STATO DEL PAGAMENTO','nl'=>'BETALINGSSTATUS','ru'=>'СТАТУС ОПЛАТЫ','zh'=>'支付状态','ja'=>'決済ステータス','ko'=>'결제 상태','ar'=>'حالة الدفع','hi'=>'भुगतान स्थिति','pl'=>'STATUS PŁATNOŚCI'),
        'AWAITING SIGNATURE' => array('tr'=>'İMZA BEKLENİYOR','de'=>'WARTE AUF SIGNATUR','fr'=>'EN ATTENTE DE SIGNATURE','es'=>'ESPERANDO FIRMA','pt'=>'AGUARDANDO ASSINATURA','it'=>'IN ATTESA DI FIRMA','nl'=>'WACHTEN OP HANDTEKENING','ru'=>'ОЖИДАНИЕ ПОДПИСИ','zh'=>'等待签名','ja'=>'署名待ち','ko'=>'서명 대기 중','ar'=>'في انتظار التوقيع','hi'=>'हस्ताक्षर की प्रतीक्षा','pl'=>'OCZEKIWANIE NA PODPIS'),
        'NETWORK FEE' => array('tr'=>'AĞ ÜCRETİ','de'=>'NETZWERKGEBÜHR','fr'=>'FRAIS DE RÉSEAU','es'=>'TARIFA DE RED','pt'=>'TAXA DE REDE','it'=>'COMMISSIONE DI RETE','nl'=>'NETWERKKOSTEN','ru'=>'СЕТЕВАЯ КОМИССИЯ','zh'=>'网络费用','ja'=>'ネットワーク手数料','ko'=>'네트워크 수수료','ar'=>'رسوم الشبكة','hi'=>'नेटवर्क शुल्क','pl'=>'OPŁATA SIECIOWA'),
        'CONNECT WALLET' => array('tr'=>'CÜZDANI BAĞLA','de'=>'WALLET VERBINDEN','fr'=>'CONNECTER LE PORTEFEUILLE','es'=>'CONECTAR BILLETERA','pt'=>'CONECTAR CARTEIRA','it'=>'CONNETTI PORTAFOGLIO','nl'=>'WALLET VERBINDEN','ru'=>'ПОДКЛЮЧИТЬ КОШЕЛЁК','zh'=>'连接钱包','ja'=>'ウォレットを接続','ko'=>'지갑 연결','ar'=>'ربط المحفظة','hi'=>'वॉलेट कनेक्ट करें','pl'=>'POŁĄCZ PORTFEL'),
        'SIGN & PAY NOW' => array('tr'=>'İMZALA VE ŞİMDİ ÖDE','de'=>'SIGNIEREN & JETZT BEZAHLEN','fr'=>'SIGNER & PAYER MAINTENANT','es'=>'FIRMAR Y PAGAR AHORA','pt'=>'ASSINAR E PAGAR AGORA','it'=>'FIRMA E PAGA ORA','nl'=>'ONDERTEKEN & BETAAL NU','ru'=>'ПОДПИСАТЬ И ОПЛАТИТЬ','zh'=>'签名并立即支付','ja'=>'署名して今すぐ支払う','ko'=>'서명 및 지금 결제','ar'=>'وقّع وادفع الآن','hi'=>'साइन करें और अभी भुगतान करें','pl'=>'PODPISZ I ZAPŁAĆ TERAZ'),
        'Requires OmniXEP extension. Supports XEP, MEMEX and more.' => array('tr'=>'OmniXEP eklentisi gerektirir. XEP, MEMEX ve daha fazlasını destekler.','de'=>'Erfordert die OmniXEP-Erweiterung. Unterstützt XEP, MEMEX und mehr.','fr'=>'Nécessite l\'extension OmniXEP. Prend en charge XEP, MEMEX et plus.','es'=>'Requiere la extensión OmniXEP. Soporta XEP, MEMEX y más.','pt'=>'Requer extensão OmniXEP. Suporta XEP, MEMEX e mais.','it'=>'Richiede l\'estensione OmniXEP. Supporta XEP, MEMEX e altro.','nl'=>'Vereist de OmniXEP-extensie. Ondersteunt XEP, MEMEX en meer.','ru'=>'Требуется расширение OmniXEP. Поддерживает XEP, MEMEX и др.','zh'=>'需要OmniXEP扩展。支持XEP、MEMEX等。','ja'=>'OmniXEP拡張機能が必要です。XEP、MEMEXなどに対応。','ko'=>'OmniXEP 확장 프로그램 필요. XEP, MEMEX 등 지원.','ar'=>'يتطلب إضافة OmniXEP. يدعم XEP وMEMEX والمزيد.','hi'=>'OmniXEP एक्सटेंशन आवश्यक। XEP, MEMEX और अधिक का समर्थन।','pl'=>'Wymaga rozszerzenia OmniXEP. Obsługuje XEP, MEMEX i więcej.'),
        'Unable to fetch market rates. Please try again.' => array('tr'=>'Piyasa kurları alınamadı. Lütfen tekrar deneyin.','de'=>'Marktkurse konnten nicht abgerufen werden. Bitte erneut versuchen.','fr'=>'Impossible d\'obtenir les taux du marché. Veuillez réessayer.','es'=>'No se pudieron obtener las tasas del mercado. Intente de nuevo.','pt'=>'Não foi possível obter as taxas de mercado. Tente novamente.','it'=>'Impossibile ottenere i tassi di mercato. Riprova.','nl'=>'Marktkoersen ophalen mislukt. Probeer opnieuw.','ru'=>'Не удалось получить рыночные курсы. Попробуйте снова.','zh'=>'无法获取市场汇率，请重试。','ja'=>'市場レートを取得できません。もう一度お試しください。','ko'=>'시장 환율을 가져올 수 없습니다. 다시 시도해주세요.','ar'=>'تعذر جلب أسعار السوق. حاول مجددًa.','hi'=>'बाज़ार दरें प्राप्त नहीं हो सकीं। कृपया पुनः प्रयास करें।','pl'=>'Nie udało się pobrać kursów. Spróbuj ponownie.'),
    );
}

/**
 * Translate a string based on current language
 */
function __omnixep($text) {
    $lang = omnixep_get_current_lang();
    if ($lang === 'en') return $text;
    
    $translations = omnixep_get_translations();
    if (isset($translations[$text][$lang])) {
        return $translations[$text][$lang];
    }
    return $text;
}

/**
 * AJAX handler for saving language preference
 */
add_action('wp_ajax_omnixep_set_language', 'omnixep_ajax_set_language');
function omnixep_ajax_set_language() {
    if (!current_user_can('manage_woocommerce')) {
        wp_send_json_error('Forbidden');
    }
    $lang = sanitize_text_field($_POST['lang'] ?? 'en');
    $languages = omnixep_get_languages();
    if (!isset($languages[$lang])) {
        wp_send_json_error('Invalid language');
    }
    update_option('omnixep_admin_language', $lang);
    wp_send_json_success(array('lang' => $lang));
}
